// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY7Kk3melgyVzVUcgINkRQMvb_7BepWJc',
    appId: '1:1015524249408:android:7a18146fbeb9a3b2d074a5',
    messagingSenderId: '1015524249408',
    projectId: 'vdb-poc',
    databaseURL: 'https://vdb-poc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vdb-poc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1Pz3ajv_8EbuAGPJomhVWENp5Tfhp7fY',
    appId: '1:1015524249408:ios:3490189d7d8e03f4d074a5',
    messagingSenderId: '1015524249408',
    projectId: 'vdb-poc',
    databaseURL: 'https://vdb-poc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vdb-poc.firebasestorage.app',
    iosBundleId: 'com.gnb.homeAutomationTablet',
  );
}
